# Generated by Django 2.2.1 on 2019-06-27 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='principle',
            new_name='principal',
        ),
    ]
